export const EMAIL_TOKEN_STATUS = {
  PENDING: 'PENDING',
  CANCELLED: 'CANCELLED',
  CONFIRMED: 'CONFIRMED',
};
export const EMAIL_TYPES = {
  EMAIL_VALIDATION: 'EMAIL_VALIDATION',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
};
