#!/bin/bash

echo "Pre-commit hook started..."
for file in $(git diff --diff-filter=d --name-only | grep -E '\.(js|jsx)$')
do
  echo "<----------| $file |---------->"
  node_modules/.bin/eslint "$file" --fix # we only want to lint the staged changes, not any un-staged changes
  if [ $? -ne 0 ]; then
    exit 1 # exit with failure status
  fi
done